PR template and Simulation addition to github action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,6 +5,7 @@ name: CI
 # Controls when the action will run. Triggers the workflow on push or pull request
 # events but only for the main branch.
 on:
+  workflow_dispatch:
   push:
     branches: [ main ]
   pull_request:
@@ -40,3 +41,14 @@ jobs:
     # Runs a single command using the runners shell
     - name: Compile and run tests on robot code
       run: ./gradlew build
+
+    # Runs a simulation to spot check crashes
+    - name: Run simulation to check for runtime errors
+      run: timeout 1m ./gradlew simulateJava 2>&1 | awk -v rc=0 '/The robot program quit unexpectedly/ { rc=1 } 1; END {exit rc}'
+      # 1. Run simulation with 1 minute timeout
+      # 2. Redirect stderr to stdout (just in case)
+      # 3. Use awk to check for robot crash message and set the return code based on this. (Alternative to grep that doesn't filter the simulation output)
+      # Awk One-liner stolen from https://stackoverflow.com/questions/27447705/grep-without-filtering 
+
+    - name: Git Clean Check
+      run: test -z "$(git status --porcelain)" || { git diff; exit 1; }
